"""create administrative foundation

Revision ID: 0001_foundation
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_foundation"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rental_activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_name", sa.String(length=200), nullable=False),
        sa.Column("siren", sa.String(length=9), nullable=True),
        sa.Column("siret", sa.String(length=14), nullable=True),
        sa.Column("activity_start_date", sa.Date(), nullable=False),
        sa.Column("tax_regime", sa.String(length=40), nullable=False),
        sa.Column("accounting_method", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "accounting_method = 'ACCRUAL'", name=op.f("ck_rental_activity_accounting_method")
        ),
        sa.CheckConstraint(
            "siren IS NULL OR (length(siren) = 9 AND siren NOT GLOB '*[^0-9]*')",
            name=op.f("ck_rental_activity_siren_format"),
        ),
        sa.CheckConstraint(
            "siret IS NULL OR (length(siret) = 14 AND siret NOT GLOB '*[^0-9]*' AND siren IS NOT NULL AND substr(siret, 1, 9) = siren)",
            name=op.f("ck_rental_activity_siret_format"),
        ),
        sa.CheckConstraint(
            "tax_regime = 'REAL_SIMPLIFIED_BIC'", name=op.f("ck_rental_activity_tax_regime")
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_rental_activity_singleton")),
        sa.CheckConstraint(
            "length(trim(activity_name)) > 0", name=op.f("ck_rental_activity_name_required")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rental_activity")),
    )
    op.create_table(
        "fiscal_year",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rental_activity_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("fiscal_vintage", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("reopened_at", sa.DateTime(), nullable=True),
        sa.Column("reopening_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(status = 'CLOSED' AND closed_at IS NOT NULL) OR (status != 'CLOSED' AND closed_at IS NULL)",
            name=op.f("ck_fiscal_year_closure_timestamp"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'READY_TO_CLOSE', 'CLOSED')", name=op.f("ck_fiscal_year_status")
        ),
        sa.CheckConstraint(
            "(reopened_at IS NULL AND reopening_reason IS NULL) OR (reopened_at IS NOT NULL AND reopening_reason IS NOT NULL AND length(trim(reopening_reason)) > 0)",
            name=op.f("ck_fiscal_year_reopening_reason"),
        ),
        sa.CheckConstraint(
            "length(trim(fiscal_vintage)) > 0", name=op.f("ck_fiscal_year_vintage_required")
        ),
        sa.CheckConstraint("start_date <= end_date", name=op.f("ck_fiscal_year_date_order")),
        sa.CheckConstraint("year BETWEEN 1900 AND 9999", name=op.f("ck_fiscal_year_year_range")),
        sa.ForeignKeyConstraint(
            ["rental_activity_id"],
            ["rental_activity.id"],
            name=op.f("fk_fiscal_year_rental_activity_id_rental_activity"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fiscal_year")),
        sa.UniqueConstraint(
            "rental_activity_id", "year", name=op.f("uq_fiscal_year_rental_activity_id")
        ),
    )
    with op.batch_alter_table("fiscal_year", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fiscal_year_rental_activity_id"), ["rental_activity_id"], unique=False
        )

    op.create_table(
        "property",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rental_activity_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("acquisition_date", sa.Date(), nullable=False),
        sa.Column("rental_start_date", sa.Date(), nullable=True),
        sa.Column("acquisition_price", sa.Integer(), nullable=False),
        sa.Column("acquisition_costs", sa.Integer(), nullable=False),
        sa.Column("land_value", sa.Integer(), nullable=False),
        sa.Column("building_value", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "typeof(acquisition_costs) = 'integer' AND acquisition_costs >= 0",
            name=op.f("ck_property_acquisition_costs"),
        ),
        sa.CheckConstraint(
            "typeof(acquisition_price) = 'integer' AND acquisition_price >= 0",
            name=op.f("ck_property_acquisition_price"),
        ),
        sa.CheckConstraint(
            "typeof(building_value) = 'integer' AND building_value >= 0",
            name=op.f("ck_property_building_value"),
        ),
        sa.CheckConstraint(
            "typeof(land_value) = 'integer' AND land_value >= 0",
            name=op.f("ck_property_land_value"),
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_property_name_required")),
        sa.ForeignKeyConstraint(
            ["rental_activity_id"],
            ["rental_activity.id"],
            name=op.f("fk_property_rental_activity_id_rental_activity"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property")),
    )
    with op.batch_alter_table("property", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_property_rental_activity_id"), ["rental_activity_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("property", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_property_rental_activity_id"))

    op.drop_table("property")
    with op.batch_alter_table("fiscal_year", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fiscal_year_rental_activity_id"))

    op.drop_table("fiscal_year")
    op.drop_table("rental_activity")
    # ### end Alembic commands ###
