"""business operations banking and loans

Revision ID: 0003_operations
Revises: 0002_ledger
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0003_operations"
down_revision: str | None = "0002_ledger"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


GUARDS = {
    "business_operation_update": "CREATE TRIGGER operations_business_operation_update BEFORE UPDATE ON business_operation BEGIN SELECT RAISE(ABORT,'BUSINESS_RECORD_IMMUTABLE'); END",
    "business_operation_delete": "CREATE TRIGGER operations_business_operation_delete BEFORE DELETE ON business_operation BEGIN SELECT RAISE(ABORT,'BUSINESS_RECORD_IMMUTABLE'); END",
    "bank_transaction_update": "CREATE TRIGGER operations_bank_transaction_update BEFORE UPDATE ON bank_transaction BEGIN SELECT RAISE(ABORT,'BUSINESS_RECORD_IMMUTABLE'); END",
    "bank_transaction_delete": "CREATE TRIGGER operations_bank_transaction_delete BEFORE DELETE ON bank_transaction BEGIN SELECT RAISE(ABORT,'BUSINESS_RECORD_IMMUTABLE'); END",
    "loan_update": "CREATE TRIGGER operations_loan_update BEFORE UPDATE ON loan BEGIN SELECT RAISE(ABORT,'BUSINESS_RECORD_IMMUTABLE'); END",
    "loan_delete": "CREATE TRIGGER operations_loan_delete BEFORE DELETE ON loan BEGIN SELECT RAISE(ABORT,'BUSINESS_RECORD_IMMUTABLE'); END",
    "bank_account_update": "CREATE TRIGGER operations_bank_account_update BEFORE UPDATE ON bank_account BEGIN SELECT RAISE(ABORT,'BUSINESS_RECORD_IMMUTABLE'); END",
    "bank_account_delete": "CREATE TRIGGER operations_bank_account_delete BEFORE DELETE ON bank_account BEGIN SELECT RAISE(ABORT,'BUSINESS_RECORD_IMMUTABLE'); END",
    "business_insert": "CREATE TRIGGER operations_business_insert BEFORE INSERT ON business_operation BEGIN\n SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM accounting_entry e JOIN fiscal_year y ON y.id=e.fiscal_year_id\n WHERE e.id=NEW.accounting_entry_id AND e.status='VALIDATED' AND y.status='OPEN'\n AND e.fiscal_year_id=NEW.fiscal_year_id AND e.accounting_date=NEW.date\n AND e.source_type=NEW.kind AND e.source_id=NEW.request_id\n AND (SELECT SUM(debit) FROM accounting_entry_line WHERE accounting_entry_id=e.id)=NEW.amount)\n THEN RAISE(ABORT,'BUSINESS_LEDGER_MISMATCH') END;\n SELECT CASE WHEN NEW.kind='LOAN_PAYMENT' AND\n (NEW.principal+NEW.interest+NEW.insurance+NEW.other_costs!=NEW.amount OR NEW.loan_id IS NULL)\n THEN RAISE(ABORT,'LOAN_SPLIT_INVALID') END;\nEND",
    "match_insert": "CREATE TRIGGER operations_match_insert BEFORE INSERT ON bank_match BEGIN\n SELECT CASE WHEN NOT EXISTS(\n SELECT 1 FROM bank_transaction t JOIN bank_account b ON b.id=t.bank_account_id\n JOIN accounting_entry_line l ON l.id=NEW.entry_line_id\n JOIN accounting_entry e ON e.id=l.accounting_entry_id JOIN fiscal_year y ON y.id=e.fiscal_year_id\n WHERE t.id=NEW.transaction_id AND l.account_number=b.account_number AND l.debit-l.credit=t.amount\n AND e.status='VALIDATED' AND y.status='OPEN' AND t.date BETWEEN y.start_date AND y.end_date\n AND e.accounting_date=t.date\n AND NOT EXISTS(SELECT 1 FROM accounting_entry WHERE reversal_of_id=e.id AND status='VALIDATED'))\n THEN RAISE(ABORT,'BANK_MATCH_INVALID') END;\nEND",
    "match_update": "CREATE TRIGGER operations_match_update BEFORE UPDATE ON bank_match BEGIN SELECT RAISE(ABORT,'MATCH_IMMUTABLE'); END",
    "match_delete": "CREATE TRIGGER operations_match_delete BEFORE DELETE ON bank_match\n WHEN (SELECT y.status FROM accounting_entry_line l JOIN accounting_entry e ON e.id=l.accounting_entry_id\n JOIN fiscal_year y ON y.id=e.fiscal_year_id WHERE l.id=OLD.entry_line_id)!='OPEN'\n BEGIN SELECT RAISE(ABORT,'EXERCISE_LOCKED'); END",
    "matched_reversal": "CREATE TRIGGER operations_matched_reversal BEFORE UPDATE ON accounting_entry\n WHEN NEW.status='VALIDATED' AND NEW.reversal_of_id IS NOT NULL\n AND EXISTS(SELECT 1 FROM bank_match m JOIN accounting_entry_line l ON l.id=m.entry_line_id\n WHERE l.accounting_entry_id=NEW.reversal_of_id)\n BEGIN SELECT RAISE(ABORT,'MATCHED_ENTRY_REQUIRES_UNMATCH'); END",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("account_number", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_number"],
            ["account.number"],
            name=op.f("fk_bank_account_account_number_account"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_account")),
        sa.UniqueConstraint("account_number", name=op.f("uq_bank_account_account_number")),
    )
    op.create_table(
        "bank_transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bank_account_id", sa.Integer(), nullable=False),
        sa.Column("external_reference", sa.String(length=200), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("import_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "typeof(amount)='integer' AND amount!=0", name=op.f("ck_bank_transaction_amount")
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_account.id"],
            name=op.f("fk_bank_transaction_bank_account_id_bank_account"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_transaction")),
        sa.UniqueConstraint(
            "bank_account_id",
            "external_reference",
            name=op.f("uq_bank_transaction_bank_account_id"),
        ),
    )
    op.create_table(
        "loan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("property_id", sa.Integer(), nullable=False),
        sa.Column("lender", sa.String(length=200), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("initial_principal", sa.Integer(), nullable=False),
        sa.Column("interest_rate_basis_points", sa.Integer(), nullable=False),
        sa.Column("duration_months", sa.Integer(), nullable=False),
        sa.Column("monthly_payment", sa.Integer(), nullable=False),
        sa.Column("monthly_insurance", sa.Integer(), nullable=False),
        sa.Column("principal_account", sa.String(length=10), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "typeof(initial_principal)='integer' AND initial_principal>0",
            name=op.f("ck_loan_principal"),
        ),
        sa.CheckConstraint(
            "duration_months>0 AND interest_rate_basis_points>=0", name=op.f("ck_loan_terms")
        ),
        sa.CheckConstraint(
            "typeof(monthly_payment)='integer' AND monthly_payment>=0 AND "
            "typeof(monthly_insurance)='integer' AND monthly_insurance>=0",
            name=op.f("ck_loan_monthly_terms"),
        ),
        sa.ForeignKeyConstraint(
            ["principal_account"],
            ["account.number"],
            name=op.f("fk_loan_principal_account_account"),
        ),
        sa.ForeignKeyConstraint(
            ["property_id"], ["property.id"], name=op.f("fk_loan_property_id_property")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loan")),
        sa.UniqueConstraint("principal_account", name=op.f("uq_loan_principal_account")),
    )
    op.create_table(
        "business_operation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("property_id", sa.Integer(), nullable=False),
        sa.Column("fiscal_year_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("counterparty", sa.String(length=200), nullable=False),
        sa.Column("accounting_account", sa.String(length=10), nullable=False),
        sa.Column("bank_account_id", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("loan_id", sa.Integer(), nullable=True),
        sa.Column("accounting_entry_id", sa.Integer(), nullable=False),
        sa.Column("deductible_basis_points", sa.Integer(), nullable=False),
        sa.Column("fiscal_treatment", sa.String(length=40), nullable=False),
        sa.Column("principal", sa.Integer(), nullable=False),
        sa.Column("interest", sa.Integer(), nullable=False),
        sa.Column("insurance", sa.Integer(), nullable=False),
        sa.Column("other_costs", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('REVENUE','EXPENSE','SETTLEMENT','LOAN_PAYMENT','LOAN_FUNDING')",
            name=op.f("ck_business_operation_kind"),
        ),
        sa.CheckConstraint(
            "typeof(amount)='integer' AND amount>0", name=op.f("ck_business_operation_amount")
        ),
        sa.CheckConstraint(
            "typeof(insurance)='integer' AND insurance>=0",
            name=op.f("ck_business_operation_insurance"),
        ),
        sa.CheckConstraint(
            "typeof(interest)='integer' AND interest>=0",
            name=op.f("ck_business_operation_interest"),
        ),
        sa.CheckConstraint(
            "typeof(other_costs)='integer' AND other_costs>=0",
            name=op.f("ck_business_operation_other_costs"),
        ),
        sa.CheckConstraint(
            "typeof(principal)='integer' AND principal>=0",
            name=op.f("ck_business_operation_principal"),
        ),
        sa.CheckConstraint(
            "deductible_basis_points BETWEEN 0 AND 10000",
            name=op.f("ck_business_operation_percentage"),
        ),
        sa.CheckConstraint(
            "(fiscal_treatment='REQUIRES_REVIEW') OR "
            "(fiscal_treatment='DEDUCTIBLE' AND deductible_basis_points=10000) OR "
            "(fiscal_treatment='NON_DEDUCTIBLE' AND deductible_basis_points=0) OR "
            "(fiscal_treatment='PARTIAL' AND deductible_basis_points BETWEEN 1 AND 9999)",
            name=op.f("ck_business_operation_fiscal_metadata"),
        ),
        sa.CheckConstraint(
            "kind='LOAN_PAYMENT' OR (principal=0 AND interest=0 AND insurance=0 AND other_costs=0)",
            name=op.f("ck_business_operation_loan_components"),
        ),
        sa.ForeignKeyConstraint(
            ["accounting_account"],
            ["account.number"],
            name=op.f("fk_business_operation_accounting_account_account"),
        ),
        sa.ForeignKeyConstraint(
            ["accounting_entry_id"],
            ["accounting_entry.id"],
            name=op.f("fk_business_operation_accounting_entry_id_accounting_entry"),
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_account.id"],
            name=op.f("fk_business_operation_bank_account_id_bank_account"),
        ),
        sa.ForeignKeyConstraint(
            ["fiscal_year_id"],
            ["fiscal_year.id"],
            name=op.f("fk_business_operation_fiscal_year_id_fiscal_year"),
        ),
        sa.ForeignKeyConstraint(
            ["loan_id"], ["loan.id"], name=op.f("fk_business_operation_loan_id_loan")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["business_operation.id"],
            name=op.f("fk_business_operation_parent_id_business_operation"),
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_business_operation_property_id_property"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_operation")),
        sa.UniqueConstraint(
            "accounting_entry_id", name=op.f("uq_business_operation_accounting_entry_id")
        ),
        sa.UniqueConstraint("request_id", name=op.f("uq_business_operation_request_id")),
    )
    op.create_table(
        "bank_match",
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("entry_line_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_line_id"],
            ["accounting_entry_line.id"],
            name=op.f("fk_bank_match_entry_line_id_accounting_entry_line"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["bank_transaction.id"],
            name=op.f("fk_bank_match_transaction_id_bank_transaction"),
        ),
        sa.PrimaryKeyConstraint("transaction_id", name=op.f("pk_bank_match")),
        sa.UniqueConstraint("entry_line_id", name=op.f("uq_bank_match_entry_line_id")),
    )
    op.create_index(op.f("ix_loan_property_id"), "loan", ["property_id"])
    op.create_index(
        op.f("ix_bank_transaction_bank_account_id"), "bank_transaction", ["bank_account_id"]
    )
    op.create_index(
        op.f("ix_business_operation_property_id"), "business_operation", ["property_id"]
    )
    op.create_index(
        op.f("ix_business_operation_fiscal_year_id"), "business_operation", ["fiscal_year_id"]
    )
    op.create_index(
        op.f("ix_business_operation_bank_account_id"), "business_operation", ["bank_account_id"]
    )
    op.create_index(op.f("ix_business_operation_parent_id"), "business_operation", ["parent_id"])
    op.create_index(op.f("ix_business_operation_loan_id"), "business_operation", ["loan_id"])
    # ### end Alembic commands ###

    for sql in GUARDS.values():
        op.execute(sql)


def downgrade() -> None:
    connection = op.get_bind()
    for table in ("business_operation", "bank_transaction", "bank_account", "loan"):
        if connection.execute(sa.select(sa.func.count()).select_from(sa.table(table))).scalar():
            raise RuntimeError("Cannot discard business records through downgrade")
    for name in GUARDS:
        op.execute(f"DROP TRIGGER operations_{name}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bank_match")
    op.drop_index(op.f("ix_business_operation_loan_id"), table_name="business_operation")
    op.drop_index(op.f("ix_business_operation_parent_id"), table_name="business_operation")
    op.drop_index(op.f("ix_business_operation_bank_account_id"), table_name="business_operation")
    op.drop_index(op.f("ix_business_operation_fiscal_year_id"), table_name="business_operation")
    op.drop_index(op.f("ix_business_operation_property_id"), table_name="business_operation")
    op.drop_table("business_operation")
    op.drop_index(op.f("ix_loan_property_id"), table_name="loan")
    op.drop_table("loan")
    op.drop_index(op.f("ix_bank_transaction_bank_account_id"), table_name="bank_transaction")
    op.drop_table("bank_transaction")
    op.drop_table("bank_account")
    # ### end Alembic commands ###
